# Generated by Django 4.0.2 on 2022-02-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMINISTRATOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdministratorId', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ADMINISTRATORACTIVITYLOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdministratorId', models.CharField(max_length=50)),
                ('DateTimestamp', models.CharField(max_length=50)),
                ('Action', models.CharField(max_length=50)),
                ('IPAddress', models.CharField(max_length=50)),
                ('HostName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FLIGHTPAYMENTS',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('CardNumber', models.CharField(max_length=50)),
                ('CVV', models.CharField(max_length=50)),
                ('ExpiryDate', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FLIGHTTICKETS',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('FlightNumber', models.CharField(max_length=50)),
                ('TravelClass', models.CharField(max_length=50)),
                ('CheckinOpens', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Departure', models.CharField(max_length=50)),
                ('Arrival', models.CharField(max_length=50)),
                ('DepartingFrom', models.CharField(max_length=50)),
                ('DepartureAirportandTerminal', models.CharField(max_length=50)),
                ('ArrivingAt', models.CharField(max_length=50)),
                ('ArrivalAirportandTerminal', models.CharField(max_length=50)),
                ('Barcode', models.CharField(max_length=50)),
                ('TicketValidity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HOTELBOOKING',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('HotelName', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Travelers', models.CharField(max_length=50)),
                ('Rooms', models.CharField(max_length=50)),
                ('RoomType', models.CharField(max_length=50)),
                ('CheckIn', models.CharField(max_length=50)),
                ('CheckOut', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ONEWAYFLIGHTS',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('TripType', models.CharField(max_length=50)),
                ('LeavingFrom', models.CharField(max_length=50)),
                ('GoingTo', models.CharField(max_length=50)),
                ('Departing', models.CharField(max_length=50)),
                ('Adults', models.CharField(max_length=50)),
                ('Children', models.CharField(max_length=50)),
                ('FlightType', models.CharField(max_length=50)),
                ('Airline', models.CharField(max_length=50)),
                ('TravelClass', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ROUNDTRIPFLIGHTS',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('TripType', models.CharField(max_length=50)),
                ('LeavingFrom', models.CharField(max_length=50)),
                ('GoingTo', models.CharField(max_length=50)),
                ('Departing', models.CharField(max_length=50)),
                ('Returning', models.CharField(max_length=50)),
                ('Adults', models.CharField(max_length=50)),
                ('Children', models.CharField(max_length=50)),
                ('FlightType', models.CharField(max_length=50)),
                ('Airline', models.CharField(max_length=50)),
                ('TravelClass', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USERACTIVITYLOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('DateTimestamp', models.CharField(max_length=50)),
                ('Action', models.CharField(max_length=50)),
                ('IPAddress', models.CharField(max_length=50)),
                ('HostName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
                ('DateAdded', models.CharField(max_length=50)),
            ],
        ),
    ]
